In [1]:
import pandas as pd

In [2]:
play=pd.read_csv('C:/Users/welcome/Desktop/playdata.csv')

In [3]:
play.head(10)

   DAY   OUTLOOK    TEMP HUMIDITY    WIND  PLAYBOLL
0    1     SUNNY     HOT     HIGH    WEAK         1
1    2     SUNNY     HOT     HIGH  STRONG         1
2    3  OVERCAST     HOT     HIGH    WEAK         2
3    4      RAIN     HOT     HIGH    WEAK         2
4    5      RAIN  NORMAL   NORMAL    WEAK         2
5    6      RAIN  NORMAL   NORMAL  STRONG         1
6    7  OVERCAST  NORMAL   NORMAL  STRONG         2
7    8     SUNNY    HIGH     HIGH    WEAK         1
8    9     SUNNY  NORMAL   NORMAL    WEAK         2
9   10      RAIN  NORMAL   NORMAL    WEAK         2

In [5]:
play['TEMP'].sort_values()

7       HIGH
11      HIGH
13      HIGH
0        HOT
1        HOT
2        HOT
3        HOT
4     NORMAL
5     NORMAL
6     NORMAL
8     NORMAL
9     NORMAL
10    NORMAL
12    NORMAL
Name: TEMP, dtype: object

In [6]:
play['TEMP'].sort_values(ascending=False)

12    NORMAL
10    NORMAL
9     NORMAL
8     NORMAL
6     NORMAL
5     NORMAL
4     NORMAL
3        HOT
2        HOT
1        HOT
0        HOT
13      HIGH
11      HIGH
7       HIGH
Name: TEMP, dtype: object

In [7]:
play.sort_values(['OUTLOOK','WIND'])

    DAY   OUTLOOK    TEMP HUMIDITY    WIND  PLAYBOLL
6     7  OVERCAST  NORMAL   NORMAL  STRONG         2
11   12  OVERCAST    HIGH     HIGH  STRONG         2
2     3  OVERCAST     HOT     HIGH    WEAK         2
12   13  OVERCAST  NORMAL   NORMAL    WEAK         2
5     6      RAIN  NORMAL   NORMAL  STRONG         1
13   14      RAIN    HIGH     HIGH  STRONG         1
3     4      RAIN     HOT     HIGH    WEAK         2
4     5      RAIN  NORMAL   NORMAL    WEAK         2
9    10      RAIN  NORMAL   NORMAL    WEAK         2
1     2     SUNNY     HOT     HIGH  STRONG         1
10   11     SUNNY  NORMAL   NORMAL  STRONG         2
0     1     SUNNY     HOT     HIGH    WEAK         1
7     8     SUNNY    HIGH     HIGH    WEAK         1
8     9     SUNNY  NORMAL   NORMAL    WEAK         2

In [8]:
play.TEMP.str.lower()

0        hot
1        hot
2        hot
3        hot
4     normal
5     normal
6     normal
7       high
8     normal
9     normal
10    normal
11      high
12    normal
13      high
Name: TEMP, dtype: object

In [9]:
play.TEMP.str.upper()

0        HOT
1        HOT
2        HOT
3        HOT
4     NORMAL
5     NORMAL
6     NORMAL
7       HIGH
8     NORMAL
9     NORMAL
10    NORMAL
11      HIGH
12    NORMAL
13      HIGH
Name: TEMP, dtype: object

In [10]:
play.TEMP.str.contains('HOT')

0      True
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
Name: TEMP, dtype: bool